pipeline{
    agent any
    tools {
        maven 'Maven 3.9.11' // Replace 'Maven 3.9.6' with the name you gave your Maven installation
    }

    stages{
        stage('Checkout') {
            steps {
            checkout scmGit(branches: [[name: '*/dev-master']], extensions: [], userRemoteConfigs: [[credentialsId: 'd1462202-56f4-4824-b942-ba88dc35836d', url: 'https://github.com/naveenbiz227/currency-exchange-service']])
            }
        }

          stage('Build') {
            steps {
                // Build the Spring Boot application using Maven
                sh 'mvn clean install'
            }
        }

         stage('Build Docker Image') {
            steps {
//                     # Copy the new jar to the build location
                    cp -f /target/devops-integrfation.jar pipeline/jenkins/build/

                    echo "****************************"
                    echo "** Building Docker Image ***"
                    echo "****************************"

                    cd jenkins/build/ && docker-compose -f docker-compose-build.yml build --no-cache
            }
        }
    }
}